wikilabels:
  form_directory: forms/enabled
  form_i18n_directory: forms/i18n

wsgi:
  host: localhost:8080
  application_root: ""
  url_prefix: ""

database:
  host: localhost
  dbname: wikilabels

oauth:
  mw_uri: https://www.mediawiki.org/w/index.php

wikis:
  testwiki:
    db_name: 'testwiki'
    wiki_path: 'test.wikipedia.org'
    lang_code: 'en'
  fawiki:
    db_name: 'fawiki'
    wiki_path: 'fa.wikipedia.org'
    lang_code: 'fa'
    dir: rtl
