wikilabels:
  form_directory: forms/enabled

wsgi:
  host: localhost:8080
  application_root: "/labels"
  url_prefix: "/labels"

database:
  config: config/localdev-db-config.yaml

oauth:
  mw_uri: https://www.mediawiki.org/w/index.php
  creds: config/oauth-localdev.yaml
