wikilabels:
  form_directory: forms/enabled

wsgi:
  host: localhost:8080
  application_root: "/labels"
  url_prefix: "/labels"

database:
  host: localhost
  dbname: wikilabels
  creds: config/db-localdev.yaml

oauth:
  mw_uri: https://www.mediawiki.org/w/index.php
  creds: config/oauth-localdev.yaml
